### ISSUE TITLE
Memory leak observed when using file_observer or time_series_observer 

### ISSUE THREAD

**Issue by restenb** [open-simulation-platform/libcosim#646]
When using the file observer or unbuffered time series observer, memory use of the library is explosive over time. The issue is especially apparent when running a simulation with both, indicating that both these observers have separate memory leak problems.

**Comment by kyllingstad** [comment]
For `time_series_observer`, the problem seems to be that when we say "unbuffered" we really mean "unlimited buffer size". ;)

Regarding `file_observer`, I suspect that the `ss_` buffer never gets emptied and keeps growing (unlike the raw data buffers – `xxxSamples_` – which get cleared manually). A quick test/fix would be to turn `ss_` into a local variable inside `persist()` instead and see if that improves things.

**Comment by kyllingstad** [comment]
Fixed by #647.
