### ISSUE TITLE
Should FMI Enum values be ignored or should we fail fast when encountering them?

### ISSUE THREAD

**Issue by THEvang** [open-simulation-platform/libcosim#670]
I know that we don't support enum values in the model description files and it seems like they are now just ignored when encountered. The user is given a warning, but the importer continues, ignoring the variable. Is this a safe way of doing it? Couldn't the user potentially start a simulation where an important variable is ignored? 

Should we just fail fast when encountering enums?

https://github.com/open-simulation-platform/libcosim/blob/22a89c439970a2e2588ed5e90082e6e892274aeb/src/cosim/fmi/v1/fmu.cpp#L77-L79

**Comment by kyllingstad** [comment]
If memory serves me right, this was done because we had some actual cases where we needed to use third-party FMUs that had enum parameters, but we didn't actually need to interact with those parameters in any way. Simply forbidding the use of those FMUs seemed like the worst option then, and we didn't have the time to implement proper enum support, so issuing a warning was chosen as a pragmatic solution.

**Comment by eidekrist** [comment]
Closing issue following discussion in OSP committee meeting
